# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultfee',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultfee',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Patient'),
        ),
    ]
