# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
        ('patientmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='visitreson',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='testsresults',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='symtomes',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='reportfiles',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='referalls',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='patientstatus',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='patientproblems',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='patientallert',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='medications',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='inpatientdetails',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='illnesssymtoms',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='goals',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='amendments',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='allerirs',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='alert',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='advancederivatives',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
    ]
