# Generated by Django 2.2.5 on 2019-10-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20191014_1415'),
        ('patientmanagement', '0002_auto_20190809_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='appointments.Appointmentrequest'),
        ),
    ]
