# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMedicineFromDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('expiryDate', models.DateTimeField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationName',
            fields=[
                ('name', models.CharField(help_text=b'Commercial Name (e.g. Viagra)', max_length=255, primary_key=True, serialize=False)),
                ('active_substances', django_extensions.db.fields.json.JSONField(blank=True, default=[], help_text=b'List of active substances')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MedicationNDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc', models.CharField(db_index=True, max_length=12, unique=True)),
                ('manufacturer', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationStrength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', django_extensions.db.fields.json.JSONField(blank=True, default={}, help_text=b'For example:\n    {\n        \x93Sildenafil\x94: { \x93strength\x94: 3, \x93unit\x94: \x93mg/1\x94 }\n    }\n    ')),
                ('medication_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='pharmacy.MedicationName')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiryDate', models.DateTimeField(null=True)),
                ('genericName', models.CharField(max_length=255)),
                ('medicineDetails', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referenceLink', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=255)),
                ('referredDoctorName', models.CharField(max_length=255)),
                ('stockAvailable', models.PositiveIntegerField(blank=True, null=True)),
                ('saleStatus', models.CharField(blank=True, choices=[(b'PAID', b'Paid'), (b'NOTPAID', b'Notpaid'), (b'CANCELLED', b'Cancelled')], default=b'NOTPAID', max_length=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicinescategory', to='pharmacy.MedicineCategory')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='pharmacy.CustomerType')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSalesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicinecategory', to='pharmacy.MedicineCategory')),
                ('medicineName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medname', to='pharmacy.Medicine')),
                ('medicinelist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_list', to='pharmacy.MedicineSale')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStoreLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineCategory', models.CharField(max_length=255)),
                ('storeLocation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('fulfillmentDate', models.DateTimeField(null=True)),
                ('batchNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('expiryDate', models.DateTimeField(blank=True, null=True)),
                ('costPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('maxRetailPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('orderStatus', models.CharField(choices=[(b'RECEIVED', b'Received'), (b'RETURNED', b'Returned'), (b'CANCELLED', b'Cancelled'), (b'ORDERED', b'Ordered')], default=b'ORDERED', max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine', to='pharmacy.Medicine')),
                ('medicineCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medcategory', to='pharmacy.MedicineCategory')),
                ('paymentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='pharmacy.PaymentOption')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTaxOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseTax', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('altPhoneNumber', models.CharField(max_length=20)),
                ('landlineNumber', models.CharField(max_length=20)),
                ('contactPerson', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchaseTax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax', to='pharmacy.PurchaseTaxOption'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='pharmacy.Supplier'),
        ),
        migrations.AddField(
            model_name='medicinesale',
            name='paymentOption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentOption', to='pharmacy.PaymentOption'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='pharmacy.MedicineCategory'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StoreLocation', to='pharmacy.MedicineStoreLocation'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedSupplier', to='pharmacy.Supplier'),
        ),
        migrations.AddField(
            model_name='medicationndc',
            name='medication_strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndcs', to='pharmacy.MedicationStrength'),
        ),
        migrations.AddField(
            model_name='addmedicinefromdb',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medcategorys', to='pharmacy.MedicineCategory'),
        ),
        migrations.AddField(
            model_name='addmedicinefromdb',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StoreLocations', to='pharmacy.MedicineStoreLocation'),
        ),
        migrations.AddField(
            model_name='addmedicinefromdb',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medname', to='pharmacy.MedicationName'),
        ),
        migrations.AddField(
            model_name='addmedicinefromdb',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedSuppliers', to='pharmacy.Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together=set([('name', 'category')]),
        ),
    ]
