# Generated by Django 2.2.5 on 2019-09-11 10:24

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationname',
            name='active_substances',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=[], help_text='List of active substances'),
        ),
        migrations.AlterField(
            model_name='medicationname',
            name='name',
            field=models.CharField(help_text='Commercial Name (e.g. Viagra)', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicationstrength',
            name='strength',
            field=django_extensions.db.fields.json.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='medicinesale',
            name='saleStatus',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('NOTPAID', 'Notpaid'), ('CANCELLED', 'Cancelled')], default='NOTPAID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='orderStatus',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('ORDERED', 'Ordered')], default='ORDERED', max_length=10),
        ),
    ]
