# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotchoices', models.TextField(blank=True, null=True)),
                ('bookingdate', models.DateField(null=True)),
                ('bookingtime', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datechoice', models.DateField(blank=True, null=True, unique=True)),
                ('choices', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctortimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('consultationfee', models.IntegerField(null=True)),
                ('breakstart', models.TimeField(blank=True, null=True)),
                ('breakend', models.TimeField(blank=True, null=True)),
                ('appointmnetduration', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
