# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimes',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Doctors'),
        ),
        migrations.AddField(
            model_name='choices',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Doctors'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Doctors'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.Patient'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='standardchoices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Choices'),
        ),
    ]
