# Generated by Django 2.2.5 on 2019-10-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20190809_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='usermanagement.Patient'),
        ),
    ]
