# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 05:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 9, 5), null=True),
        ),
    ]
