# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20190905_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 9, 11), null=True),
        ),
    ]
