# Generated by Django 2.2.5 on 2019-09-12 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20190911_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 9, 12), null=True),
        ),
    ]
