# Generated by Django 2.2.5 on 2019-09-16 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_auto_20190912_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 9, 16), null=True),
        ),
    ]
