# Generated by Django 2.2.5 on 2019-09-26 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_auto_20190924_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 9, 26), null=True),
        ),
    ]
