# Generated by Django 2.2.5 on 2019-10-01 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_auto_20190926_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 10, 1), null=True),
        ),
    ]
