# Generated by Django 2.2.5 on 2019-10-04 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_auto_20191001_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 10, 4), null=True),
        ),
    ]
